Repository Mika215/to-do-list-app-group-3, pull requests merged in 2021-08, with the labels that each got.

#15 Add btn
  .eslintrc.json
  client/src/init/index.js
  index.html
  package-lock.json
  package.json
  planning/backlog.md
  planning/wireframe/wireframe.png
Labels: HTML, JS

#17 Css file done
  client/styles/index.css
Labels: CSS

#20 Editing README.md and wireframe, adding favicon
  client/public/favicon.svg
  client/public/option1.png
  client/public/option2.png
  client/public/screenshot-www.w3schools.com-2021.08.16-17_07_05.png
  client/src/init/index.js
  planning/README.md
  planning/wireframe/wireframe.png
Labels: enhancement

#21 updating README.md
  .vscode/settings.json
  README.md
  planning/communication-plan.md
Labels: enhancement

#24 Changes in my availability.
  planning/communication-plan.md
Labels: documentation

#25 Major rearrangement add-btn
  client/src/init/index.js
  index.html
  v8-compile-cache-0/9.2.230.21-node.19/zShomezShyfzSDocumentszShyf-linuxzSprojectszSseparation-of-concerns-starterzSnode_moduleszSeslintzSbinzSeslint.js.BLOB
  v8-compile-cache-0/9.2.230.21-node.19/zShomezShyfzSDocumentszShyf-linuxzSprojectszSseparation-of-concerns-starterzSnode_moduleszSeslintzSbinzSeslint.js.MAP
Labels: help wanted

#34 Test btn
  client/src/handlers/delete-btn.js
  client/src/init/index.js
  client/src/listeners/delete-btn.js
  client/src/logic/delete-btn.js
  docs/dependency-graph.html
Labels: handler, listener
